# Site settings
title: CS Melange
email: 
author: varshaneya
description: "Cocktail of articles from various disciplines of Computer Science"
full_description: "Reverie on machine learning, high performance computing, image processing and system software."
baseurl: ""
url: "http://varshaneya.github.io"
linkedin_username: varshaneya
github_username:  varshaneya

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
