# Site settings
title: CS Melange
email: "varshaneya.v@gmail.com"
author: varshaneya
description: "A compilation of my thoughts and observations on various disciplines of Computer Science."
 
disclaimer: >
 All of the articles have code written by me with links to appropriate GitHub repositories. You are free to use my code for academic purposes only after giving appropriate credits.
 I have also mentioned the reference(s) that is(are) used in all the articles.
 
categories: ["High Performance Computing", "Misc"]
baseurl: ""
url: "http://varshaneya.github.io"
linkedin_username: varshaneya
github_username:  varshaneya

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
