title: "CS Melange"
author:
  name: varshaneya
  email: "varshaneya.v@gmail.com"
  url: "https://varshaneya.github.io/"
description: A compilation of my observations and views on various topics in computer science.

#twitter_username: jekyllrb
github_username: varshaneya
baseurl: /
# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
