# Site settings
title: CS Melange
email: 
description: "Musings on machine learning, high performance computing, image processing and system software."
baseurl: ""
url: "http://varshaneya.github.io"
#twitter_username: karpathy
github_username:  varshaneya

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
